version: '3.2'

services:
  portainer:
    image: portainer/portainer:1.16.3
    command: --no-auth
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      webnet:

  fastdock:
    image: pymet/fastdock:2.0
    volumes:
      - fastdock_data:/etc/ssh
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authorized_keys:/keys/root:ro
    networks:
      webnet:

  nginx:
    image: nginx:1.13.9
    depends_on:
      - portainer
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/htpasswd
      - ./ssl.key:/etc/nginx/ssl.key
      - ./ssl.crt:/etc/nginx/ssl.crt
    ports:
      - 12000:443
    networks:
      webnet:

volumes:
  portainer_data:
  fastdock_data:

networks:
  webnet:
